version: "3"
services:
  euchre-frontend:
    image: "ghcr.io/mikekutzma/euchre/euchre.euchre-frontend:latest"
    build:
      dockerfile: ./euchre-frontend/Dockerfile
      context: .
      args:
        - DOTENV_FILE=.env.prod
    ports:
      - "5040:80"
  euchre-api:
    image: "ghcr.io/mikekutzma/euchre/euchre.euchre-api:latest"
    build:
      dockerfile: ./euchre-api/Dockerfile
      context: .
      args:
        - DOTENV_FILE=.env.prod
    ports:
      - "5041:5041"
    secrets:
      - redispasswd
  euchre-ai:
    image: "ghcr.io/mikekutzma/euchre/euchre.euchre-ai:latest"
    build:
      dockerfile: ./euchre-ai/Dockerfile
      context: .
      args:
        - DOTENV_FILE=.env.prod
    depends_on:
      - euchre-api
  euchre-redis:
    image: "ghcr.io/mikekutzma/euchre/euchre.euchre-redis:latest"
    build:
      dockerfile: ./redis/Dockerfile
      context: .
      args:
        - DOTENV_FILE=.env.prod
    secrets:
      - redispasswd
    volumes:
      - /var/redisdata:/data

secrets:
  redispasswd:
    file: ./redispasswd.txt
